### ISSUE TITLE
Configuration file format support

### ISSUE THREAD

**Issue by djmattyg007** [dshearer/jobber#14]
Is there a reason you can't support both YAML and JSON? A lot of people (myself included) would rather use JSON instead of YAML. Given this module appears to have once supported JSON, it seems odd that support for it would be completely removed instead of just supporting both formats.

**Comment by dshearer** [comment]
You're right that the jobber file was originally in JSON.  I switched to YAML b/c I felt that JSON was quite verbose.    A big advantage to YAML is that you can plop a whole shell script into the "cmd" attribute without having to escape quotes, as long as you add appropriate whitespace at the beginning of each line.  But then, a disadvantage is that, if you're not familiar with YAML, the syntax is not obvious.

Why do you prefer JSON?

I'm reluctant to support both since it adds complexity without (I think) a huge benefit.

**Comment by dshearer** [comment]
By the way, at the very beginning one had to name each time component in the config file, thus:

     [
        {
            "name": "Echo",
            "cmd": "(echo \"Hello\" >> result) && whoami",
            "time": { "sec": 0, "min": 0 }
        }
    ]

I switch to the cron way of specifying the time b/c I figured it would be more familiar to ppl.  What do you think would be best?
