### ISSUE TITLE
Error parsing config file

### ISSUE THREAD

**Issue by blacklabelops** [dshearer/jobber#20]
I get the following error:

~~~~
Failed to load jobs for yaml: line 3: did not find expected alphabetic or numeric character: jobber
~~~~

with the following config file:

~~~~
---
- name: TestEcho
  cmd: trigger
  time: * * * * * *
  onError: Stop
  notifyOnError: true
  notifyOnFailure: true
~~~~

Full log:

~~~~
Launching.
Loaded 0 new jobs for root.
Loaded 0 new jobs for bin.
Loaded 0 new jobs for daemon.
Loaded 0 new jobs for adm.
Loaded 0 new jobs for lp.
Loaded 0 new jobs for sync.
Loaded 0 new jobs for shutdown.
Loaded 0 new jobs for halt.
Loaded 0 new jobs for mail.
Loaded 0 new jobs for operator.
Loaded 0 new jobs for games.
Loaded 0 new jobs for ftp.
Loaded 0 new jobs for nobody.
Loaded 0 new jobs for systemd-bus-proxy.
Loaded 0 new jobs for systemd-network.
Loaded 0 new jobs for dbus.
Failed to load jobs for open /dev/null/.jobber: not a directory: tss
Failed to load jobs for yaml: line 3: did not find expected alphabetic or numeric character: jobber
Loaded 0 new jobs for jobber_client.
totalJobs: -2; len(m.jobs): 0
New context: 0.0
Main thread context: 0.0
New context: 0.0.0
~~~~

**Comment by blacklabelops** [comment]
Managed to trace it down to the time definition. Seems like the parser does not accept it. I have to leave the definition empty in order to achieve something like "every second".

**Comment by dshearer** [comment]
As always, apologies for the delay.

Here's what's happening: as the YAML parser begins to parse the value for the "time" key, it sees that the first char is "*".  As it turns out, "*" is a keyword in YAML used to reference other nodes (cf. http://www.yaml.org/spec/1.2/spec.html#* alias//).  So if your "time" string begins with "*", you'll need to enclose the whole thing in (single or double) quotes:
```
---
- name: TestEcho
  cmd: trigger
  time: '* * * * * *'
  onError: Stop
  notifyOnError: true
  notifyOnFailure: true
```

Gross.  

I chose YAML over JSON so that you can include multi-line shell scripts in the "cmd" value, but its complexities are starting to bug me.

**Comment by blacklabelops** [comment]
I still think yaml is a good choice for a config file. Much more comprehensive and readable than json.

**Comment by blacklabelops** [comment]
Fixed my container according to your proposal, '* * * * * *' is working now perfectly.
