### ISSUE TITLE
Running jobs in the host machine's time zone

### ISSUE THREAD

**Issue by LINKIWI** [dshearer/jobber#79]
So I currently have a command set to run at 12 AM daily, using the following time specifier:

```
0 0 0 * * *
```

Over the last few days, Jobber has been successfully and consistently running the job at 12 AM daily, which is great....but at 12 AM UTC. The host machine's system time zone is America/Chicago. How can I configure the time zone of the job, or just make it use the host machine's time zone?

I understand UTC is standard but this is quite confusing esp. for installations where the host machine is not in the UTC time zone (which most are not). However I'm happy to submit a PR documenting that the time specifier uses UTC by default.

**Comment by RomRider** [comment]
I did that with a new Dockerfile : 
```
FROM blacklabelops/jobber:XXXXXXXX

RUN apk add --update tzdata && \
	rm -rf /var/cache/apk/* && rm -rf /tmp/* && rm -rf /var/log/*
```
Then you can use your new image to start the container, and use -e TZ=Europe/Paris for example on the command line to have your container running with the timezone you want.

**Comment by LINKIWI** [comment]
Thanks for your comment--my infrastructure does not make use of Docker and I just want Jobber to use the host machine's time zone. Any suggestions?

**Comment by dshearer** [comment]
I'll look into this... it should be using the host's timezone.

**Comment by dshearer** [comment]
So, what actually happens is that Jobber _does_ interpret the jobfile in terms of the local timezone --- BUT, if the local timezone changes, Jobber will not know about it, and will continue interpreting jobfiles in terms of the original local timezone.  To get it to notice the new local timezone, you need to restart the Jobber service.

I'd like to have notice notice local timezone changes, but this is not supported in Go.  Implementing this myself would be a PITA.  So for now I don't think I'll change the way jobfiles are interpreted.  What I _can_ do is change 'jobber list' so that it includes the timezone in 'next run time'.

**Comment by techtonik** [comment]
> So, what actually happens is that Jobber does interpret the jobfile in terms of the local timezone

It is possible to explicitly set UTC time?
